-- =============================================================================
--  Hotel Rate Intelligence - database schema
--  Run this in the Supabase SQL editor (or `supabase db push`) BEFORE seed.sql.
--
--  Tables:
--    properties     - the luxury hotels we track (public read)
--    rate_history   - historical nightly prepaid rates per property (public read)
--    collections    - a user's saved properties (row-level owned by auth.uid())
--
--  Row Level Security is ON for every table. Properties and rate history are
--  world-readable; collections are private to their owner.
-- =============================================================================

-- ---------------------------------------------------------------------------
--  properties
-- ---------------------------------------------------------------------------
create table if not exists public.properties (
  id            text        primary key,            -- human-readable slug, used in /property/[id]
  name          text        not null,
  destination   text        not null,
  country       text        not null,
  description   text        not null default '',
  star_rating   smallint    not null default 5,
  current_rate  numeric     not null,               -- current prepaid nightly rate
  avg_rate      numeric     not null,               -- platform's historical average
  currency      text        not null default 'USD', -- ISO 4217
  accent_from   text        not null default '#1d1d28', -- gradient fallback (from)
  accent_to     text        not null default '#262633', -- gradient fallback (to)
  image_url     text        not null default '',        -- hero photo (Unsplash CDN)
  brand_id      text        not null default '',        -- references brands(id)
  tags          text[]      not null default '{}',      -- experience tag ids
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
--  rate_history
-- ---------------------------------------------------------------------------
create table if not exists public.rate_history (
  id           bigint generated by default as identity primary key,
  property_id  text        not null references public.properties (id) on delete cascade,
  captured_on  date        not null,
  rate         numeric     not null,
  unique (property_id, captured_on)
);

create index if not exists rate_history_property_idx
  on public.rate_history (property_id, captured_on);

-- ---------------------------------------------------------------------------
--  collections (saved properties, one row per user+property)
-- ---------------------------------------------------------------------------
create table if not exists public.collections (
  id           uuid        primary key default gen_random_uuid(),
  user_id      uuid        not null references auth.users (id) on delete cascade,
  property_id  text        not null references public.properties (id) on delete cascade,
  created_at   timestamptz not null default now(),
  unique (user_id, property_id)
);

create index if not exists collections_user_idx on public.collections (user_id);

-- =============================================================================
--  Row Level Security
-- =============================================================================
alter table public.properties   enable row level security;
alter table public.rate_history enable row level security;
alter table public.collections  enable row level security;

-- properties: anyone (including anonymous) may read; nobody writes via the API.
drop policy if exists "properties are publicly readable" on public.properties;
create policy "properties are publicly readable"
  on public.properties for select
  using (true);

-- rate_history: publicly readable.
drop policy if exists "rate history is publicly readable" on public.rate_history;
create policy "rate history is publicly readable"
  on public.rate_history for select
  using (true);

-- collections: a user may only see / create / delete their own rows.
drop policy if exists "users read their own collection" on public.collections;
create policy "users read their own collection"
  on public.collections for select
  using (auth.uid() = user_id);

drop policy if exists "users add to their own collection" on public.collections;
create policy "users add to their own collection"
  on public.collections for insert
  with check (auth.uid() = user_id);

drop policy if exists "users remove from their own collection" on public.collections;
create policy "users remove from their own collection"
  on public.collections for delete
  using (auth.uid() = user_id);

-- =============================================================================
--  Reference data: brands (hotel groups) and experience tags. Both are
--  world-readable. The running app also ships these as bundled reference data
--  so it renders without a backend.
-- =============================================================================
create table if not exists public.brands (
  id          text    primary key,
  name        text    not null,
  origin      text    not null default '',
  founded     int,
  description text    not null default ''
);

create table if not exists public.tags (
  id        text primary key,
  label     text not null,
  category  text not null default 'Experience' -- Setting | Style | Experience
);

alter table public.brands enable row level security;
alter table public.tags   enable row level security;

drop policy if exists "brands are publicly readable" on public.brands;
create policy "brands are publicly readable"
  on public.brands for select using (true);

drop policy if exists "tags are publicly readable" on public.tags;
create policy "tags are publicly readable"
  on public.tags for select using (true);
