"""Mermaid source extraction + offline SVG rendering.

The diagram skill always returns valid Mermaid SOURCE (generated by the LLM). A
DOWNLOADABLE rendered SVG is produced when a LOCAL renderer is available - the
Mermaid CLI (``mmdc``), which renders fully offline (no network at request time).
If ``mmdc`` is not installed the source is still returned and the frontend can
render it client-side (and still offer a "download .mmd" affordance).

No external/cloud rendering service is ever called (that would be an outbound
dependency and is forbidden on this public demo).
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable

logger = logging.getLogger("app.mermaid")

# A renderer takes Mermaid source and returns SVG text, or None if it cannot
# render. Injected so tests can render deterministically without mmdc.
MermaidRenderer = Callable[[str], "str | None"]


def extract_mermaid_source(text: str) -> str:
    """Pull clean Mermaid source out of a model response.

    Strips a ```mermaid ...``` (or plain ```) code fence if present; otherwise
    returns the trimmed text. The model is prompted to emit only the source, but
    this defends against it wrapping the diagram in a fence or adding prose.

    Also handles a DANGLING opening fence with no closing ``` - the common case
    when ``max_tokens`` truncates the response mid-diagram. Without this the raw
    ``` markers leak into the returned source and the client render fails.
    """
    s = (text or "").strip()
    if "```" not in s:
        return s
    parts = s.split("```")
    # parts[1] is the fenced content in BOTH cases:
    #   - complete fence:  [before, "<lang>\n<source>", after, ...] (len >= 3)
    #   - DANGLING open fence with no close (max_tokens truncation):
    #                      [before, "<lang>\n<source...>"]           (len == 2)
    # The old code required len(parts) >= 3 and so returned the raw text WITH the
    # ``` marker for the truncated case, breaking the client render.
    block = parts[1]
    lines = block.splitlines()
    # Drop an optional language tag on the opening fence line.
    if lines and lines[0].strip().lower() in {"mermaid", "mmd"}:
        lines = lines[1:]
    cleaned = "\n".join(lines).strip()
    # Belt-and-braces: never return anything still carrying a fence marker.
    return cleaned.strip("`").strip()


def render_svg_with_mmdc(source: str, *, timeout: float = 20.0) -> str | None:
    """Render Mermaid source to SVG using the local ``mmdc`` CLI (offline).

    Returns the SVG text, or None if mmdc is unavailable or rendering fails.
    Never raises - rendering is best-effort and degrades to source-only.
    """
    mmdc = shutil.which("mmdc")
    if not mmdc:
        return None
    tmpdir = tempfile.mkdtemp(prefix="mermaid-")
    in_path = os.path.join(tmpdir, "diagram.mmd")
    out_path = os.path.join(tmpdir, "diagram.svg")
    try:
        with open(in_path, "w", encoding="utf-8") as fh:
            fh.write(source)
        proc = subprocess.run(
            [mmdc, "-i", in_path, "-o", out_path, "-b", "transparent"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        if proc.returncode != 0 or not os.path.exists(out_path):
            logger.debug(
                "mmdc render failed rc=%s: %s", proc.returncode, proc.stderr[:200]
            )
            return None
        with open(out_path, encoding="utf-8") as fh:
            return fh.read()
    except (subprocess.TimeoutExpired, OSError) as exc:
        logger.debug("mmdc render error: %s", exc)
        return None
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def default_renderer(source: str) -> str | None:
    """Best-effort offline SVG render (mmdc when present, else None)."""
    return render_svg_with_mmdc(source)
